site_name: 宝捷信立式注塑机
site_url: https://qq3101233.github.io/github/
theme:
  name: material
  #language: zh-CN
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
docs_dir: docs
plugins:
  - search
  - mermaid2